name: flutter_application_1
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
version: 1.0.0+1

environment:
  sdk: ^3.10.8

dependencies:
  flutter:
    sdk: flutter
  sqflite: ^2.3.0  # Сама база данных
  path: ^1.8.3     # Помощник для поиска путей к файлам на Android/iOS
  google_fonts: ^6.1.0
  intl: ^0.20.2  
  provider: ^6.1.1
  fl_chart: ^0.66.0
  shared_preferences: ^2.2.2
  mobile_scanner: ^5.1.0
  pdf: ^3.10.4
  printing: ^5.11.1
  local_auth: ^2.3.0
  flutter_local_notifications: ^17.2.2
  timezone: ^0.9.2
  flutter_timezone: ^3.0.1
  flutter_localizations:
    sdk: flutter
  shimmer: ^3.0.0
  confetti: ^0.8.0
  http: ^1.2.0
  cupertino_icons: ^1.0.8
  html: ^0.15.6
  permission_handler: ^11.3.1 # 💡 Добавлено для выбивания разрешений на уведомления

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.4.0

# Настройки для иконки
flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon.png" # Базовая картинка для iOS и старых Android
  adaptive_icon_background: "#F8F9FA" # Цвет фона для новых Android (от 8.0+)
  adaptive_icon_foreground: "assets/icon_foreground.png" # Прозрачный логотип для новых Android

flutter_native_splash:
  color: "#F8F9FA" 
  image: "assets/icon_foreground.png" 
  android: true
  ios: true

# The following section is specific to Flutter packages.
flutter:
  uses-material-design: true

  # 💡 Подключаем локальные файлы (иконки для сплеш-скрина и шрифт для PDF)
  assets:
    - assets/icon.png
    - assets/icon_foreground.png
    - assets/fonts/Roboto-Regular.ttf